server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ******
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL

jsoup-connect-settings:
  userAgent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
  referrer: http://www.google.com

other-settings:
  pauseBeforeRequest: 500
  minPercentagePagesToExcludeLemmas: 100
  maxWordsBefore: 15
  maxWordsAfter: 15
  errorMessageIndexingStoppedByUser: Индексация остановлена пользователем
  errorMessageIsAlreadyStarted: Индексация уже запущена
  errorMessageIsNotRunning: Индексация не запущена
  errorPageLocatedOutsideSites: Данная страница находится за пределами сайтов, указанных в конфигурационном файле
  errorMessageEmptySearchQuery: Задан пустой поисковый запрос

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
